# Generated by Django 3.2.6 on 2021-08-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albums_name', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicsApp.artists')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicsApp.albums')),
            ],
        ),
    ]
