# Generated by Django 3.2.6 on 2021-08-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0002_albums_songs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
