# Generated by Django 3.2.6 on 2021-08-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0003_auto_20210812_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='votes',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='artist',
            name='artists_age',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='artist',
            name='artists_nationality',
            field=models.CharField(default='spain', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artists_name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
