# Generated by Django 3.2.6 on 2021-08-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0004_auto_20210812_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='albums',
            new_name='artist',
        ),
    ]
