# Generated by Django 3.2.6 on 2021-08-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0005_rename_albums_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='songs',
            new_name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
