# Generated by Django 3.2.6 on 2021-08-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0006_auto_20210812_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_type',
            field=models.CharField(choices=[(1, 'romantic'), (2, 'rock'), (3, 'soul')], default=1, max_length=200),
        ),
    ]
