# Generated by Django 3.2.6 on 2021-08-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0007_song_song_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artist_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='album_id',
        ),
    ]
