# Generated by Django 3.2.6 on 2021-08-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0008_auto_20210812_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artists_age',
            new_name='artist_age',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artists_name',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artists_nationality',
            new_name='artist_nationality',
        ),
    ]
