# Generated by Django 3.2.6 on 2021-08-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0010_artist_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='.images/'),
        ),
    ]
