# Generated by Django 3.2.6 on 2021-08-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0017_alter_artist_artist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_image',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image_URL',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_nationality',
            field=models.CharField(default='Canaidian', max_length=200),
        ),
    ]
