# Generated by Django 3.2.6 on 2021-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0018_auto_20210813_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_image_URL',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=200),
        ),
    ]
