# Generated by Django 3.2.6 on 2021-08-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0019_auto_20210813_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_image_URL',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
