# Generated by Django 3.2.6 on 2021-08-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0020_alter_artist_artist_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_image_URL',
            field=models.CharField(default='please enter the image URL here', max_length=1000),
        ),
    ]
