# Generated by Django 3.2.6 on 2021-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0021_alter_artist_artist_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_type',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
