# Generated by Django 3.2.6 on 2021-08-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0022_alter_song_song_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_type',
            field=models.CharField(choices=[(1, 'romantic'), (2, 'rock'), (3, 'soul')], default=1, max_length=200),
        ),
    ]
