# Generated by Django 3.2.6 on 2021-08-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0024_alter_song_song_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_type',
            field=models.CharField(choices=[('romantic', '1'), ('rock', '2'), ('soul', '3'), ('classical', '4'), ('folk', '5'), ('hip hop', '6')], default='1', max_length=20),
        ),
    ]
