# Generated by Django 3.2.6 on 2021-08-14 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicsApp', '0026_alter_song_song_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album_id',
        ),
        migrations.AddField(
            model_name='album',
            name='song_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicsApp.song'),
        ),
        migrations.AddField(
            model_name='artist',
            name='album_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicsApp.album'),
        ),
    ]
